---
- name: Install powertoys
  hosts: winservers
  gather_facts: false
  tasks:
    - name: Install powertoys
      win_chocolatey:
        name: powertoys
        version: '0.71.0'
        state: present
        ignore_checksums: yes
