---
- name: "Google Chrome installation on WINDOWS"
  hosts: winserverscloud
  tasks:
    - name: Install Google Chrome
      win_chocolatey:
        name: googlechrome
        state: present
        ignore_checksums: yes