---
 - name: NotePad++ installation on WINDOWS
   hosts: winserverscloud
   gather_facts: false
   tasks:
     - name: Install Notepad++ with Chocolatey module
       win_chocolatey:
        name: notepadplusplus
        state: latest
        install_args: "/D=C:\Notepad++"
        
